### PR TITLE
Tooltip Delay Feature

### PR DESCRIPTION
**Pull request by akhuoa**
This PR is for delaying the tooltip on the mouse move. The delay is added as an option in the `loadMap` method and tested on integration with `flatmapvuer`.

#### Example

```JS
mapManager.loadMap(
  ...,
  {
    ...,
    tooltipDelay: 15,
  }
);
```

### CODE REVIEW

**Comment by dbrnz** [comment]
Thanks @akhuoa. What need does this address?

I also prefer to minimise the number of package dependences -- why pull in `lodash` when `setTimeout()` can be used for the delay?

**Comment by akhuoa** [comment]
Thanks, @dbrnz, for the review. 

I'm improving the user experience when hovering over the map area by preventing multiple tooltips from flashing when the mouse is moved quickly. By introducing a delay in mouse movement, the tooltips will only appear with a slight delay when the user hovers over a specific area, preventing them from flashing when the mouse is moved rapidly over the map.
Since this feature is introduced as an optional setting, it will only affect the current behaviour if explicitly enabled.

I've replaced the `lodash` and used `debounce` as a function.

**Comment by dbrnz** [comment]
Maybe `delay()` is a better name for the utility function, since this is what it does, but otherwise all good.

**Comment by akhuoa** [comment]
The function name has been updated.

**Comment by dbrnz** [comment]
What is your time-frame for having a new release with this in it? Thanks.

**Comment by akhuoa** [comment]
I've checked with Alan. It's not urgent. You'll be able to include it in your next feature release. Thank you.

**Pull request merged**
